// Package config loads the main YAML configuration plus mandatory env vars.
package config

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// Config is the top-level panel configuration. Only bootstrap-required
// values live here — anything an admin might tune (cron cadence, JWT TTLs,
// rate limits, login mode, branding, sub_base_url, etc.) is stored in the
// settings table and edited through Admin → Settings.
type Config struct {
	Listen        string `yaml:"listen"`
	JWTSecret     string `yaml:"jwt_secret"`
	EncryptionKey string `yaml:"encryption_key"`

	MySQL MySQLConfig `yaml:"mysql"`

	ConfigDir string `yaml:"config_dir"`
	DataDir   string `yaml:"data_dir"`
}

// MySQLConfig is the database selection block. Two ways to configure:
//
//  1. Discrete fields (Host/Port/User/Password/Database/Params): readable,
//     idiomatic YAML. The panel assembles a DSN at startup.
//  2. DSN: a raw go-sql-driver MySQL DSN, OR "sqlite:./path.db" to force
//     SQLite, OR empty to fall through to embedded SQLite at
//     <DataDir>/panel.db. When DSN is non-empty it overrides the discrete
//     fields entirely.
//
// Env PSP_MYSQL_DSN, when set, replaces whatever this block produces —
// useful for keeping the password out of the config file.
type MySQLConfig struct {
	// Raw DSN escape hatch. Empty unless you need a connection-string form
	// the discrete fields don't model (e.g. unix socket, TLS).
	DSN string `yaml:"dsn"`

	// Discrete connection fields. Host being non-empty is the trigger that
	// switches the panel from SQLite (default) to MySQL.
	Host     string `yaml:"host"`
	Port     int    `yaml:"port"`
	User     string `yaml:"user"`
	Password string `yaml:"password"`
	Database string `yaml:"database"`
	// go-sql-driver query string appended to the assembled DSN. Defaults to
	// "parseTime=true&charset=utf8mb4&loc=Local" when blank — parseTime is
	// REQUIRED or GORM hands back []byte for DATETIME columns.
	Params string `yaml:"params"`
}

// LoadOrGenerate loads config from path. If the file does not exist a default
// config (with a random JWT secret) is written there first, so the panel can
// start without any manual setup.
func LoadOrGenerate(path string) (*Config, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return nil, err
	}
	if _, err := os.Stat(abs); errors.Is(err, os.ErrNotExist) {
		if err := writeDefaultConfig(abs); err != nil {
			return nil, fmt.Errorf("generate default config %s: %w", abs, err)
		}
	}
	return Load(path)
}

func writeDefaultConfig(abs string) error {
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return err
	}
	secret, err := randomBase64(32)
	if err != nil {
		return err
	}
	const tpl = `# Auto-generated by passwall-sub-panel on first run.
# This file only stores what the binary needs to BOOT: the listen address,
# the JWT signing key, where data goes on disk, and how to reach the DB.
# Everything else (login mode, branding, sub_base_url, email domains, cron
# cadence, JWT TTLs, rate limits, audit retention, SAML/OIDC, …) is managed
# from Admin → Settings and stored in the database.

# ---- Networking ----
listen: ":8788"                            # bind address; ":port" listens on all interfaces

# ---- Secrets ----
# JWT signing key. Generated randomly on first run. Rotate by replacing the
# value (invalidates every existing session). Env override: PSP_JWT_SECRET.
jwt_secret: "%s"

# Database secret encryption key. Generated randomly on first run. It protects
# 3X-UI credentials, SAML/OIDC secrets, and SMTP passwords at rest.
# Env override: PSP_ENCRYPTION_KEY.
encryption_key: "%s"

# ---- Filesystem ----
config_dir: "./config"                     # runtime configs (templates, etc.)
data_dir: "./data"                         # SQLite panel.db lives here when no MySQL is set

# ---- Database ----
# Recommended: a real MySQL 5.7+ / MariaDB 10.5+ server. Fill in the discrete
# fields below — the panel assembles the DSN for you. Uncomment the mysql:
# block to enable.
#
# mysql:
#   host: "127.0.0.1"                      # MySQL server hostname or IP
#   port: 3306                             # MySQL TCP port (3306 by default)
#   user: "psp"                            # MySQL account
#   password: "CHANGE_ME"                  # MySQL password — keep this file 0600
#   database: "passwall"                   # database/schema name (must already exist)
#   params: ""                             # extra DSN params; blank uses the
#                                          # safe default below — only override
#                                          # if you know you need something else.
#                                          # Default: parseTime=true&charset=utf8mb4&loc=Local
#
# Env override: PSP_MYSQL_DSN, if set, replaces whatever this block produces.
# Recommended for production so secrets stay out of the config file.
#
# Advanced / escape hatch: set "dsn:" to a raw go-sql-driver string when the
# discrete fields don't fit (unix socket, TLS, multi-host, etc.). When set,
# dsn wins over the discrete fields above.
#   dsn: "user:pw@unix(/tmp/mysql.sock)/db?parseTime=true"
#
# Dev/single-user fallback: leave the entire mysql block commented out and
# the panel uses embedded SQLite at <data_dir>/panel.db. You can also force
# a specific SQLite path via dsn:
#   dsn: "sqlite:./data/panel.db"
`
	encKey, err := randomBase64(32)
	if err != nil {
		return err
	}
	return os.WriteFile(abs, []byte(fmt.Sprintf(tpl, secret, encKey)), 0o600)
}

func randomBase64(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

func Load(path string) (*Config, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return nil, err
	}
	b, err := os.ReadFile(abs)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", abs, err)
	}
	var c Config
	if err := yaml.Unmarshal(b, &c); err != nil {
		return nil, fmt.Errorf("parse %s: %w", abs, err)
	}
	c.applyDefaults()

	// env overrides
	if dsn := os.Getenv("PSP_MYSQL_DSN"); dsn != "" {
		c.MySQL.DSN = dsn
	}
	if sec := os.Getenv("PSP_JWT_SECRET"); sec != "" {
		c.JWTSecret = sec
	}
	if key := os.Getenv("PSP_ENCRYPTION_KEY"); key != "" {
		c.EncryptionKey = key
	}

	if err := c.validate(); err != nil {
		return nil, err
	}
	return &c, nil
}

// SecretKeyMaterial returns stable key material used to derive the AES-GCM key
// for database secrets. Existing configs without encryption_key fall back to
// jwt_secret for compatibility; new generated configs include a separate key.
func (c *Config) SecretKeyMaterial() string {
	if strings.TrimSpace(c.EncryptionKey) != "" {
		return c.EncryptionKey
	}
	return c.JWTSecret
}

func (c *Config) applyDefaults() {
	if c.Listen == "" {
		c.Listen = ":8788"
	}
	if c.ConfigDir == "" {
		c.ConfigDir = "./config"
	}
	if c.DataDir == "" {
		c.DataDir = "./data"
	}
}

func (c *Config) validate() error {
	if c.JWTSecret == "" {
		return fmt.Errorf("jwt_secret must be set (in config or env PSP_JWT_SECRET)")
	}
	// DSN is optional; empty falls back to SQLite at <DataDir>/panel.db.
	return nil
}

// DBKind returns the active database driver: "mysql" or "sqlite".
//
// Selection rules, in order:
//  1. DSN with "sqlite:" prefix → sqlite
//  2. Any other non-empty DSN → mysql
//  3. Host is set → mysql (discrete fields)
//  4. Otherwise → sqlite (embedded zero-config fallback)
func (c *Config) DBKind() string {
	dsn := strings.TrimSpace(c.MySQL.DSN)
	if strings.HasPrefix(dsn, "sqlite:") {
		return "sqlite"
	}
	if dsn != "" {
		return "mysql"
	}
	if strings.TrimSpace(c.MySQL.Host) != "" {
		return "mysql"
	}
	return "sqlite"
}

// DBDSN returns the driver-specific connection string:
//   - For SQLite, a filesystem path (config "sqlite:..." prefix stripped, or
//     <DataDir>/panel.db when unset).
//   - For MySQL, either the raw DSN or one assembled from the discrete
//     Host/Port/User/Password/Database/Params fields.
func (c *Config) DBDSN() string {
	dsn := strings.TrimSpace(c.MySQL.DSN)
	if strings.HasPrefix(dsn, "sqlite:") {
		return strings.TrimPrefix(dsn, "sqlite:")
	}
	if dsn != "" {
		return dsn
	}
	if strings.TrimSpace(c.MySQL.Host) != "" {
		port := c.MySQL.Port
		if port <= 0 {
			port = 3306
		}
		params := strings.TrimSpace(c.MySQL.Params)
		if params == "" {
			params = "parseTime=true&charset=utf8mb4&loc=Local"
		}
		return fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?%s",
			c.MySQL.User, c.MySQL.Password,
			strings.TrimSpace(c.MySQL.Host), port,
			strings.TrimSpace(c.MySQL.Database), params)
	}
	return filepath.Join(c.DataDir, "panel.db")
}
